/*
 * Copyright (c) 2026 Opolopo Eniyan
 * Distributed under the MIT software license, see the accompanying
 * file LICENSE or http://www.opensource.org/licenses/mit-license.php.
 */

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.1.0"
}

dependencies {
//    implementation("org.apache.commons:commons-text")
//    implementation(project(":utilities"))
    implementation("com.google.code.gson:gson:2.13.2")

    implementation("org.testfx:testfx-core:4.0.18")
    implementation("org.testfx:testfx-junit5:4.0.18")
    implementation(platform("org.testfx:openjfx-monocle:21.0.2"))
}

application {
    // Define the main class for the application.
    mainModule = "com.peerdrop.desktop"
    mainClass = "com.peerdrop.desktop.Launcher"
    applicationDefaultJvmArgs = listOf(
        "--enable-native-access=javafx.graphics",
        "-Djava.net.preferIPv4Stack=true"
    )
}

javafx {
    version = "25"
    modules("javafx.controls", "javafx.fxml")
}
