/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.1.0"
}

dependencies {
//    implementation("org.apache.commons:commons-text")
//    implementation(project(":utilities"))
    implementation("com.google.code.gson:gson:2.13.2")
}

application {
    // Define the main class for the application.
    mainModule = "com.peerdrop.desktop"
    mainClass = "com.peerdrop.desktop.Launcher"
    applicationDefaultJvmArgs = listOf(
        "--enable-native-access=javafx.graphics",
        "-Djava.net.preferIPv4Stack=true"
    )
}

javafx {
    version = "25"
    modules("javafx.controls", "javafx.fxml")
}
