/*
 * This source file was generated by the Gradle 'init' task
 */
package com.peerdrop.desktop;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
